# Site settings
title: "پیغام خطای 0x12F"
motto: "نوشته شده توسط کیانوش نقوی"
author: Kianoosh Naghavi
email: naghavi.kianoosh@gmail.com
baseurl: "https://theskn.github.io" # the subpath of your site, e.g. /blog
url: "http://blog.kianooshnaghavi.com" # the base hostname & protocol for your site
keywords: ""
copyright: "Commons Attribution 4.0 International"
robot: ""
description: > # this means to ignore newlines until "baseurl:"


long_description: >

  
twitter_username: kianooshnaghavi
github_username:  theskn
fullname: "کیانوش نقوی"
favicon: "favicon.png"


#outputting
permalink: :title.html

# Build settings
markdown: kramdown
kramdown:
    coderay_line_numbers: nil
encoding: utf-8
timezone: Europe/Berlin

paginate: 5
paginate_path: "/page:num/"

tag_page_layout: tag_page
tag_page_dir: tag

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: post
      author: "کیانوش نقوی"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "drafts" # previously `post` in Jekyll 2.2.
    values:
      layout: post
      author: "کیانوش نقوی"

gems:
  - jekyll-sitemap
  - jalalidate
  - coderay
  - jekyll-paginate

collections:
  projects:
    output: true
